{
  description = "NixOS configuration with Home Manager";

  # ── Flake inputs ─────────────────────────────────────────────────────
  #
  # Inputs are the external dependencies this flake pulls in.
  # `nix flake update` refreshes them and writes the resolved
  # versions to flake.lock.
  inputs = {
    # Track the NixOS unstable channel for the latest packages.
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Home Manager manages per-user dotfiles and programs declaratively.
    # `inputs.nixpkgs.follows` pins it to the same nixpkgs as the system
    # so everything builds against one consistent package set.
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  # ── Flake outputs ────────────────────────────────────────────────────
  #
  # This flake produces a single NixOS system configuration named "ghost".
  # `nixos-rebuild switch --flake .#ghost` builds and activates it.
  outputs = inputs @ { self, nixpkgs, home-manager, ... }:
  let
    # Absolute path to this repo on disk. Passed to modules that need
    # to reference the flake directory at runtime (e.g. the auto-upgrade
    # service and the `nh` wrapper).
    flakePath = "/home/bws428/.nixos-config";
  in {
    nixosConfigurations.ghost = nixpkgs.lib.nixosSystem {
          # specialArgs makes extra values available to every module's
          # function arguments (the { config, pkgs, ... } header).
          specialArgs = { inherit flakePath; };

          modules = [
            # ── Hardware ───────────────────────────────────────────────
            # Auto-generated by nixos-generate-config; describes disks,
            # filesystems, and CPU-specific firmware. Do not edit by hand.
            ./hardware-configuration.nix

            # ── System modules ─────────────────────────────────────────
            # Each file in modules/ owns one concern. Add a new module by
            # creating the file and appending it to this list.
            ./modules/boot.nix
            ./modules/users.nix
            ./modules/locale.nix
            ./modules/nvidia.nix
            ./modules/networking.nix
            ./modules/bluetooth.nix
            ./modules/services.nix
            ./modules/upgrade.nix

            # ── Desktop environments ───────────────────────────────────
            ./modules/desktop.nix

            # ── Fonts & packages ───────────────────────────────────────
            ./modules/fonts.nix
            ./modules/packages.nix

            # ── Home Manager ───────────────────────────────────────────
            # Integrated as a NixOS module so `nixos-rebuild` applies
            # both system and user config in one step (no separate
            # `home-manager switch` needed).
            home-manager.nixosModules.home-manager {
              # Use the system-level nixpkgs instead of a separate instance.
              home-manager.useGlobalPkgs = true;
              # Install user packages to /etc/profiles (visible to systemd, etc.)
              home-manager.useUserPackages = true;
              # Pass flakePath into Home Manager modules the same way
              # we do for NixOS modules above.
              home-manager.extraSpecialArgs = { inherit flakePath; };
              home-manager.users.bws428 = {
                imports = [
                  ./home.nix
                ];
              };
            }
          ];
        };
      };
}
