{
  description = "NixOS configuration with Home Manager";

  # ── Flake inputs ─────────────────────────────────────────────────────
  #
  # Inputs are the external dependencies this flake pulls in.
  # `nix flake update` refreshes them and writes the resolved
  # versions to flake.lock.
  inputs = {
    # Track the NixOS unstable channel for the latest packages.
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Home Manager manages per-user dotfiles and programs declaratively.
    # `inputs.nixpkgs.follows` pins it to the same nixpkgs as the system
    # so everything builds against one consistent package set.
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Patched kernel modules + firmware for the MediaTek MT7927
    # (Filogic 380) WiFi/BT card. Mainline support is not yet merged.
    mt7927.url = "github:clemenscodes/linux-mt7927";

    # Noctalia v5 — native C++/OpenGL ES Wayland shell (bar, launcher,
    # lock screen, notifications). Not yet in nixpkgs; consumed from the
    # upstream flake. Deliberately NOT following our nixpkgs: doing so
    # would rebuild against a different package set and forfeit the
    # noctalia.cachix.org binary cache (substituters in desktop.nix).
    noctalia.url = "github:noctalia-dev/noctalia";

    # Noctalia greeter — greetd login screen matching the shell's look.
    # Separate upstream repo with its own flake + NixOS module. No
    # binary cache is published for it, so following our nixpkgs costs
    # nothing and avoids evaluating a second nixpkgs tree.
    noctalia-greeter = {
      url = "github:noctalia-dev/noctalia-greeter";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Declarative Flatpak management. Lets us list flatpaks in the
    # config and have nixos-rebuild install/update/remove them to match
    # — keeps Flathub apps in the same source-of-truth as everything else.
    nix-flatpak.url = "github:gmodena/nix-flatpak";
  };

  # ── Flake outputs ────────────────────────────────────────────────────
  #
  # This flake produces a single NixOS system configuration named "ghost".
  # `nixos-rebuild switch --flake .#ghost` builds and activates it.
  outputs = inputs @ { self, nixpkgs, home-manager, mt7927, noctalia, noctalia-greeter, nix-flatpak, ... }:
  let
    # Absolute path to this repo on disk. Passed to modules that need
    # to reference the flake directory at runtime (e.g. the auto-upgrade
    # service and the `nh` wrapper).
    flakePath = "/home/bws428/.nixos-config";
  in {
    nixosConfigurations.ghost = nixpkgs.lib.nixosSystem {
          # specialArgs makes extra values available to every module's
          # function arguments (the { config, pkgs, ... } header).
          specialArgs = { inherit flakePath mt7927; };

          modules = [
            # ── Hardware ───────────────────────────────────────────────
            # Auto-generated by nixos-generate-config; describes disks,
            # filesystems, and CPU-specific firmware. Do not edit by hand.
            ./hardware-configuration.nix

            # Out-of-tree MT7927 WiFi/BT driver (until mainline support lands).
            mt7927.nixosModules.default

            # nix-flatpak — adds services.flatpak.{packages,remotes,update,…}
            # on top of the upstream services.flatpak module.
            nix-flatpak.nixosModules.nix-flatpak

            # Noctalia greeter — adds programs.noctalia-greeter and wires
            # greetd's default_session to it (see modules/greeter.nix).
            noctalia-greeter.nixosModules.default

            # ── System modules ─────────────────────────────────────────
            # Each file in modules/ owns one concern. Add a new module by
            # creating the file and appending it to this list.
            ./modules/boot.nix
            ./modules/users.nix
            ./modules/locale.nix
            ./modules/nvidia.nix
            ./modules/networking.nix
            ./modules/mt7927-wifi.nix
            ./modules/bluetooth.nix
            ./modules/services.nix
            ./modules/storage.nix
            ./modules/backups.nix
            ./modules/upgrade.nix

            # ── Desktop environments ───────────────────────────────────
            ./modules/desktop.nix
            ./modules/greeter.nix

            # ── Fonts & packages ───────────────────────────────────────
            ./modules/fonts.nix
            ./modules/packages.nix

            # ── Development environment ────────────────────────────────
            # nix-ld, envfs, and native language toolchains (rustup,
            # nodejs, bun, uv). Lets prebuilt binaries from outside
            # nixpkgs run without per-project `nix develop` shells.
            ./modules/dev.nix

            # ── Home Manager ───────────────────────────────────────────
            # Integrated as a NixOS module so `nixos-rebuild` applies
            # both system and user config in one step (no separate
            # `home-manager switch` needed).
            home-manager.nixosModules.home-manager {
              # Use the system-level nixpkgs instead of a separate instance.
              home-manager.useGlobalPkgs = true;
              # Install user packages to /etc/profiles (visible to systemd, etc.)
              home-manager.useUserPackages = true;
              # On conflict (HM trying to write a file the user already has),
              # rename the existing file with this extension instead of
              # failing activation. Recovery: inspect *.hm-bak files and
              # delete them once you're sure HM's version is what you want.
              home-manager.backupFileExtension = "hm-bak";
              # Pass flakePath into Home Manager modules the same way
              # we do for NixOS modules above.
              home-manager.extraSpecialArgs = { inherit flakePath; };
              home-manager.users.bws428 = {
                imports = [
                  # Adds programs.noctalia.* and defaults its package to
                  # the upstream flake build (cachix-cached). Configured
                  # in config/noctalia/noctalia.nix.
                  noctalia.homeModules.default
                  ./home.nix
                ];
              };
            }
          ];
        };
      };
}
