{
  description = "NixOS configuration with Home Manager";

  # ── Flake inputs ──
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    noctalia-greeter = {
      url = "github:noctalia-dev/noctalia-greeter";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    hummingbird = {
      url = "git+https://git.mailliw.org/hummingbird/hummingbird";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nix-flatpak.url = "github:gmodena/nix-flatpak";
  };

  # ── Flake outputs ──
  # Produces a single NixOS config "ghost".
  outputs = inputs @ {
    self,
    nixpkgs,
    home-manager,
    noctalia-greeter,
    hummingbird,
    nix-flatpak,
    ...
  }: let
    flakePath = "/home/bws428/.nixos-config";
  in {
    nixosConfigurations.ghost = nixpkgs.lib.nixosSystem {
      specialArgs = {
        inherit flakePath;
        inherit hummingbird;
      };

      modules = [
        # ── Hardware ──
        # Auto-generated by `nixos-generate-config`.
        ./hardware-configuration.nix

        # ── System modules ──
        ./modules/boot.nix
        ./modules/users.nix
        ./modules/locale.nix
        ./modules/nvidia.nix
        ./modules/networking.nix
        ./modules/bluetooth.nix
        ./modules/services.nix
        ./modules/llms.nix
        ./modules/storage.nix
        ./modules/backups.nix
        ./modules/upgrade.nix
        noctalia-greeter.nixosModules.default

        # ── Desktop ──
        ./modules/desktop.nix
        ./modules/greeter.nix

        # ── Fonts & packages ──
        ./modules/fonts.nix
        ./modules/packages.nix
        nix-flatpak.nixosModules.nix-flatpak

        # ── Development ──
        ./modules/dev.nix

        # ── Home Manager ──
        home-manager.nixosModules.home-manager
        {
          home-manager.useGlobalPkgs = true;
          home-manager.useUserPackages = true;
          home-manager.backupFileExtension = "hm-bak";
          home-manager.extraSpecialArgs = {inherit flakePath;};
          home-manager.users.bws428 = {
            imports = [ ./home.nix ];
          };
        }
      ];
    };
  };
}
