{ ... }:

{
  # ── SSH client config ──────────────────────────────────────────────
  # Manages ~/.ssh/config declaratively. Currently only used to define
  # the host alias for the Synology NAS that backs the claude-nas-sync
  # script (see config/claude-nas-sync.nix).
  programs.ssh = {
    enable = true;

    matchBlocks = {
      # Static-LAN Synology used as the canonical store for ~/.claude/
      # state synced between this NixOS box and the Mac. The keypair
      # itself (id_ed25519_claudesync) is generated by hand — private
      # keys don't belong in the flake.
      "claudesync-nas" = {
        hostname = "192.168.100.72";
        user = "claudesync";
        identityFile = "~/.ssh/id_ed25519_claudesync";
        identitiesOnly = true;
        # Detect dropped connections (e.g. VPN drop mid-rsync) within
        # ~45 s instead of hanging until TCP gives up.
        serverAliveInterval = 15;
        serverAliveCountMax = 3;
      };
    };
  };
}
